package ru.twistofthemyth.craftablespawners;

import org.bukkit.Material;
import org.bukkit.entity.EntityType;

import javax.annotation.Nullable;

public class Utils {

    @Nullable
    public static EntityType eggToEntity(Material material) {
        switch (material) {
            case BAT_SPAWN_EGG:
                return EntityType.BAT;
            case BEE_SPAWN_EGG:
                return EntityType.BEE;
            case BLAZE_SPAWN_EGG:
                return EntityType.BLAZE;
            case CAT_SPAWN_EGG:
                return EntityType.CAT;
            case CAVE_SPIDER_SPAWN_EGG:
                return EntityType.CAVE_SPIDER;
            case CHICKEN_SPAWN_EGG:
                return EntityType.CHICKEN;
            case COD_SPAWN_EGG:
                return EntityType.COD;
            case COW_SPAWN_EGG:
                return EntityType.COW;
            case CREEPER_SPAWN_EGG:
                return EntityType.CREEPER;
            case DOLPHIN_SPAWN_EGG:
                return EntityType.DOLPHIN;
            case DONKEY_SPAWN_EGG:
                return EntityType.DONKEY;
            case DROWNED_SPAWN_EGG:
                return EntityType.DROWNED;
            case ELDER_GUARDIAN_SPAWN_EGG:
                return EntityType.ELDER_GUARDIAN;
            case ENDERMAN_SPAWN_EGG:
                return EntityType.ENDERMAN;
            case ENDERMITE_SPAWN_EGG:
                return EntityType.ENDERMITE;
            case EVOKER_SPAWN_EGG:
                return EntityType.EVOKER;
            case FOX_SPAWN_EGG:
                return EntityType.FOX;
            case GHAST_SPAWN_EGG:
                return EntityType.GHAST;
            case GUARDIAN_SPAWN_EGG:
                return EntityType.GUARDIAN;
            case HOGLIN_SPAWN_EGG:
                return EntityType.HOGLIN;
            case HORSE_SPAWN_EGG:
                return EntityType.HORSE;
            case HUSK_SPAWN_EGG:
                return EntityType.HUSK;
            case LLAMA_SPAWN_EGG:
                return EntityType.LLAMA;
            case MAGMA_CUBE_SPAWN_EGG:
                return EntityType.MAGMA_CUBE;
            case MOOSHROOM_SPAWN_EGG:
                return EntityType.MUSHROOM_COW;
            case MULE_SPAWN_EGG:
                return EntityType.MULE;
            case OCELOT_SPAWN_EGG:
                return EntityType.OCELOT;
            case PANDA_SPAWN_EGG:
                return EntityType.PANDA;
            case PARROT_SPAWN_EGG:
                return EntityType.PARROT;
            case PHANTOM_SPAWN_EGG:
                return EntityType.PHANTOM;
            case PIGLIN_SPAWN_EGG:
                return EntityType.PIGLIN;
            case PIGLIN_BRUTE_SPAWN_EGG:
                return EntityType.PIGLIN_BRUTE;
            case PILLAGER_SPAWN_EGG:
                return EntityType.PILLAGER;
            case POLAR_BEAR_SPAWN_EGG:
                return EntityType.POLAR_BEAR;
            case PUFFERFISH_SPAWN_EGG:
                return EntityType.PUFFERFISH;
            case RABBIT_SPAWN_EGG:
                return EntityType.RABBIT;
            case RAVAGER_SPAWN_EGG:
                return EntityType.RAVAGER;
            case SALMON_SPAWN_EGG:
                return EntityType.SALMON;
            case SHEEP_SPAWN_EGG:
                return EntityType.SHEEP;
            case SHULKER_SPAWN_EGG:
                return EntityType.SHULKER;
            case SILVERFISH_SPAWN_EGG:
                return EntityType.SILVERFISH;
            case SKELETON_SPAWN_EGG:
                return EntityType.SKELETON;
            case SKELETON_HORSE_SPAWN_EGG:
                return EntityType.SKELETON_HORSE;
            case SLIME_SPAWN_EGG:
                return EntityType.SLIME;
            case SPIDER_SPAWN_EGG:
                return EntityType.SPIDER;
            case SQUID_SPAWN_EGG:
                return EntityType.SQUID;
            case STRAY_SPAWN_EGG:
                return EntityType.STRAY;
            case STRIDER_SPAWN_EGG:
                return EntityType.STRIDER;
            case TRADER_LLAMA_SPAWN_EGG:
                return EntityType.TRADER_LLAMA;
            case TROPICAL_FISH_SPAWN_EGG:
                return EntityType.TROPICAL_FISH;
            case TURTLE_SPAWN_EGG:
                return EntityType.TURTLE;
            case VEX_SPAWN_EGG:
                return EntityType.VEX;
            case VILLAGER_SPAWN_EGG:
                return EntityType.VILLAGER;
            case VINDICATOR_SPAWN_EGG:
                return EntityType.VINDICATOR;
            case WANDERING_TRADER_SPAWN_EGG:
                return EntityType.WANDERING_TRADER;
            case WITCH_SPAWN_EGG:
                return EntityType.WITCH;
            case WITHER_SKELETON_SPAWN_EGG:
                return EntityType.WITHER_SKELETON;
            case WOLF_SPAWN_EGG:
                return EntityType.WOLF;
            case ZOGLIN_SPAWN_EGG:
                return EntityType.ZOGLIN;
            case ZOMBIE_SPAWN_EGG:
                return EntityType.ZOMBIE;
            case ZOMBIE_HORSE_SPAWN_EGG:
                return EntityType.ZOMBIE_HORSE;
            case ZOMBIE_VILLAGER_SPAWN_EGG:
                return EntityType.ZOMBIE_VILLAGER;
            case ZOMBIFIED_PIGLIN_SPAWN_EGG:
                return EntityType.ZOMBIFIED_PIGLIN;
            case PIG_SPAWN_EGG:
                return EntityType.PIG;
            default:
                return null;
        }
    }

    public static Material entityToEgg(final EntityType entityType) {
        switch (entityType) {
            case BAT:
                return Material.BAT_SPAWN_EGG;
            case BEE:
                return Material.BEE_SPAWN_EGG;
            case BLAZE:
                return Material.BLAZE_SPAWN_EGG;
            case CAT:
                return Material.CAT_SPAWN_EGG;
            case CAVE_SPIDER:
                return Material.CAVE_SPIDER_SPAWN_EGG;
            case CHICKEN:
                return Material.CHICKEN_SPAWN_EGG;
            case COD:
                return Material.COD_SPAWN_EGG;
            case COW:
                return Material.COW_SPAWN_EGG;
            case CREEPER:
                return Material.CREEPER_SPAWN_EGG;
            case DOLPHIN:
                return Material.DOLPHIN_SPAWN_EGG;
            case DONKEY:
                return Material.DONKEY_SPAWN_EGG;
            case DROWNED:
                return Material.DROWNED_SPAWN_EGG;
            case ELDER_GUARDIAN:
                return Material.ELDER_GUARDIAN_SPAWN_EGG;
            case ENDERMAN:
                return Material.ENDERMAN_SPAWN_EGG;
            case ENDERMITE:
                return Material.ENDERMITE_SPAWN_EGG;
            case EVOKER:
                return Material.EVOKER_SPAWN_EGG;
            case FOX:
                return Material.FOX_SPAWN_EGG;
            case GHAST:
                return Material.GHAST_SPAWN_EGG;
            case GUARDIAN:
                return Material.GUARDIAN_SPAWN_EGG;
            case HOGLIN:
                return Material.HOGLIN_SPAWN_EGG;
            case HORSE:
                return Material.HORSE_SPAWN_EGG;
            case HUSK:
                return Material.HUSK_SPAWN_EGG;
            case LLAMA:
                return Material.LLAMA_SPAWN_EGG;
            case MAGMA_CUBE:
                return Material.MAGMA_CUBE_SPAWN_EGG;
            case MUSHROOM_COW:
                return Material.MOOSHROOM_SPAWN_EGG;
            case MULE:
                return Material.MULE_SPAWN_EGG;
            case OCELOT:
                return Material.OCELOT_SPAWN_EGG;
            case PANDA:
                return Material.PANDA_SPAWN_EGG;
            case PARROT:
                return Material.PARROT_SPAWN_EGG;
            case PHANTOM:
                return Material.PHANTOM_SPAWN_EGG;
            case PIGLIN:
                return Material.PIGLIN_SPAWN_EGG;
            case PIGLIN_BRUTE:
                return Material.PIGLIN_BRUTE_SPAWN_EGG;
            case PILLAGER:
                return Material.PILLAGER_SPAWN_EGG;
            case POLAR_BEAR:
                return Material.POLAR_BEAR_SPAWN_EGG;
            case PUFFERFISH:
                return Material.PUFFERFISH_SPAWN_EGG;
            case RABBIT:
                return Material.RABBIT_SPAWN_EGG;
            case RAVAGER:
                return Material.RAVAGER_SPAWN_EGG;
            case SALMON:
                return Material.SALMON_SPAWN_EGG;
            case SHEEP:
                return Material.SHEEP_SPAWN_EGG;
            case SHULKER:
                return Material.SHULKER_SPAWN_EGG;
            case SILVERFISH:
                return Material.SILVERFISH_SPAWN_EGG;
            case SKELETON:
                return Material.SKELETON_SPAWN_EGG;
            case SKELETON_HORSE:
                return Material.SKELETON_HORSE_SPAWN_EGG;
            case SLIME:
                return Material.SLIME_SPAWN_EGG;
            case SPIDER:
                return Material.SPIDER_SPAWN_EGG;
            case SQUID:
                return Material.SQUID_SPAWN_EGG;
            case STRAY:
                return Material.STRAY_SPAWN_EGG;
            case STRIDER:
                return Material.STRIDER_SPAWN_EGG;
            case TRADER_LLAMA:
                return Material.TRADER_LLAMA_SPAWN_EGG;
            case TROPICAL_FISH:
                return Material.TROPICAL_FISH_SPAWN_EGG;
            case TURTLE:
                return Material.TURTLE_SPAWN_EGG;
            case VEX:
                return Material.VEX_SPAWN_EGG;
            case VILLAGER:
                return Material.VILLAGER_SPAWN_EGG;
            case VINDICATOR:
                return Material.VINDICATOR_SPAWN_EGG;
            case WANDERING_TRADER:
                return Material.WANDERING_TRADER_SPAWN_EGG;
            case WITCH:
                return Material.WITCH_SPAWN_EGG;
            case WITHER_SKELETON:
                return Material.WITHER_SKELETON_SPAWN_EGG;
            case WOLF:
                return Material.WOLF_SPAWN_EGG;
            case ZOGLIN:
                return Material.ZOGLIN_SPAWN_EGG;
            case ZOMBIE:
                return Material.ZOMBIE_SPAWN_EGG;
            case ZOMBIE_HORSE:
                return Material.ZOMBIE_HORSE_SPAWN_EGG;
            case ZOMBIE_VILLAGER:
                return Material.ZOMBIE_VILLAGER_SPAWN_EGG;
            case ZOMBIFIED_PIGLIN:
                return Material.ZOMBIFIED_PIGLIN_SPAWN_EGG;
            case PIG:
                return Material.PIG_SPAWN_EGG;
            default:
                return Material.NETHERITE_INGOT;
        }
    }
}
